name: Build

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ⚒️
    runs-on: ubuntu-latest
    container:
      image: rbenthem/gocms:0.1
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        name: Checking Out Repo 👀
      - name: Golang Build 🐹
        run: make build
      - name: Package 📦
        run: |
          mkdir gocms-ubuntu-build
          cp tmp/gocms gocms-ubuntu-build/
          cp tmp/gocms-admin gocms-ubuntu-build/
      - uses: actions/upload-artifact@v4
        with:
          name: gocms-ubuntu-build
          path: gocms-ubuntu-build
