name: Fail Fast

on: [workflow_call]

jobs:
  linters:
    name: Linters 🧑‍🔬

    runs-on: ubuntu-latest
    container:
      image: rbenthem/gocms:0.1
      options: --user 1001

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/golangci-lint
        name: Running Linters 🧪
        with:
          linters: errcheck;staticcheck;unused;gosimple;gofmt
