name: Tests

on: [workflow_call]

jobs:
  tests:
    name: Tests 🧪
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gocms
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    container:
      image: rbenthem/gocms:0.1
      options: --user 1001

    steps:
      - uses: actions/checkout@v3

      - name: Generating templ files
        run: |
          templ generate
        shell: bash

      - name: Run migrations
        run: |
          cd migrations
          GOOSE_DRIVER=mysql GOOSE_DBSTRING="root:root@tcp(mysql:3306)/gocms" goose up
        shell: bash

      - name: Running Go Tests 🧪
        run: |
          go test ./... -v
        env:
          GITHUB_ACTIONS: "true"
