name: Tests

on: [workflow_call]

jobs:
  linters:
    name: Tests 🧪

    runs-on: ubuntu-latest
    container:
      image: rbenthem/gocms:0.1
      options: --user 1001

    steps:
      - uses: actions/checkout@v3

      - name: Generating templ files
        run: |
          templ generate
        shell: bash

      - name: Running Go Tests 🧪
        run: |
          go test ./... -v
